import { Serie } from "./serie.js";
export const series: Serie[] = [
	new Serie(
	  "Stranger Things",
	  2016,
	  3,
	  "The Duffer Brothers",
	  ["Winona Ryder", "David Harbour", "Finn Wolfhard"],
	  "Netflix",
	  "Streaming",
	  "https://www.netflix.com/title/80057281",
	  "When a young boy disappears, his mother, a police chief, and his friends must confront terrifying supernatural forces in order to get him back.",
	),
	new Serie(
	  "Breaking Bad",
	  2008,
	  5,
	  "Vince Gilligan",
	  ["Bryan Cranston", "Aaron Paul", "Anna Gunn"],
	  "AMC",
	  "Streaming",
	  "https://ce.amc.com/series/breaking-bad",
	  "A high school chemistry teacher diagnosed with inoperable lung cancer turns to manufacturing and selling methamphetamine in order to secure his family's future.",
	),
	new Serie(
        "Gossip Girl", 
        2007, 
        6, 
        "Stephanie Savage, Josh Schwartz", 
        ["Blake Lively", "Leighton Meester", "Penn Badgley", "Chace Crawford"], 
        "Netflix", 
        "Streaming", 
        "https://www.netflix.com/title/70143811", 
        "The series is focused on a group of privileged teenagers who attend a prestigious high school in Upper East Side New York as their lives are constantly watched and sometimes ruined by an infamous and local blogger."),
	new Serie(
        "Élite", 
        2018, 
        7, 
        "Ramón Salazar, Dani de la Orden", 
        ["Itzan Escamilla", "Miguel Bernardeau", "Danna Paola"], 
        "Netflix", 
        "Streaming", 
        "https://www.netflix.com/title/80200942", 
        "Cuando tres jóvenes de clase obrera se matriculan en un exclusivo instituto privado, las diferencias entre ellos y los alumnos ricos darán lugar a un asesinato."),
	new Serie(
	  "Friends",
	  1994,
	  10,
	  "David Crane, Marta Kauffman",
	  ["Jennifer Aniston", "Courteney Cox", "Lisa Kudrow"],
	  "NBC",
	  "Streaming",
	  "https://www.nbc.com/friends",
	  "Follows the personal and professional lives of six twenty to thirty-something-year-old friends living in Manhattan.",
	),
	new Serie(
        "Suits", 
        2011, 
        9, 
        "James Whitmore Jr.", 
        ["Gabriel Macht", "Patrick J. Adams", "Sarah Rafferty"], 
        "Netflix", 
        "Streaming", 
        "https://www.netflix.com/title/70195800", 
        "On the run from a drug deal gone bad, brilliant college dropout Mike Ross finds himself working with Harvey Specter, one of New York City's best lawyers.")
  ];